# Generated by Django 5.0.3 on 2024-03-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200)),
                ('card_link', models.URLField()),
                ('card_rarity', models.CharField(max_length=50)),
                ('card_code', models.CharField(max_length=20)),
                ('tcg_market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcg_min_listing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcg_num_listings', models.IntegerField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.set')),
            ],
        ),
    ]
