# Generated by Django 5.0.3 on 2024-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardimage',
            name='image',
        ),
        migrations.AddField(
            model_name='cardimage',
            name='image_path',
            field=models.CharField(default='staticfiles-cdn/card-imgs/sets/default.jpg', max_length=400),
            preserve_default=False,
        ),
    ]
