# Generated by Django 5.0.3 on 2024-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_archtype_card_attribute_card_card_atk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tcg_min_listing',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tcg_num_listings',
            field=models.IntegerField(null=True),
        ),
    ]
