# Generated by Django 5.0.3 on 2024-04-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_card_tcg_market_price_and_more'),
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_probability_per_booster', models.FloatField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.set')),
            ],
        ),
    ]
